### ISSUE TITLE
Q: kernel_rsa.cl using struct bignum or integer class template for arithmetic ?

### ISSUE THREAD

**Issue by pulmark** [blawar/biginteger#1]
Just would like to know if it is possible to use class template when building code to run on GPU.
I noticed that the (deleted) kernel_rsa.cl uses other implementation for big integers (struct bignum).

So my question is, does the GPU program (ex. kernel_rsa.cl) use also integer class template for math or is the integer template only utilized for transferring data to GPU ?   

I'm new to GPU programming, just started studying the issue.

**Comment by blawar** [comment]
yes, newer toolchains support c++ templates.
